import React, { useMemo } from 'react';
import type { ReactNode } from 'react';
import { CacheProvider } from '@emotion/react';
import createCache from '@emotion/cache';

/**
 * Provides an Emotion style cache configured with the request's CSP nonce so
 * Material-UI/Emotion-generated `<style>` tags satisfy a strict
 * Content-Security-Policy (no `'unsafe-inline'` needed for styles).
 *
 * How it works:
 * 1. Server generates a unique nonce for each request.
 * 2. Nonce is injected into HTML as `<meta property="csp-nonce" content="...">`.
 * 3. This provider reads the nonce and creates an Emotion cache with it.
 * 4. All style tags generated by Emotion will include the nonce attribute.
 * 5. CSP allows styles with matching nonce: `style-src 'nonce-...'`.
 *
 * Author: AI Documentation
 * Last Updated: 2026-07-24
 */
interface CspNonceProviderProps {
    children: ReactNode;
}

/**
 * Get CSP nonce from meta tag injected by server
 * In production, this should be a unique nonce per request
 * In development, we use a static nonce for testing
 *
 * @returns The per-request nonce string read from the `<meta property="csp-nonce">`
 *   tag, or `undefined` when running outside a DOM (SSR-safety) or when the
 *   tag is missing/still holds the unreplaced `__CSP_NONCE__` build
 *   placeholder (local dev, where no CSP header is enforced).
 */
const getNonce = (): string | undefined => {
    if (typeof document === 'undefined') return undefined;

    // Try to get nonce from meta tag
    const meta = document.querySelector('meta[property="csp-nonce"]');
    const nonce = meta?.getAttribute('content');

    // If nonce is the placeholder or empty, return undefined (development mode)
    if (!nonce || nonce === '__CSP_NONCE__') {
        console.warn('CSP nonce not found or is placeholder. Using development mode.');
        return undefined; // In dev, Emotion will work without nonce
    }

    return nonce;
};

/**
 * CspNonceProvider wraps the app to provide CSP-compliant styling
 * This allows Material-UI/Emotion to work without 'unsafe-inline' in CSP
 *
 * How it works:
 * 1. Server generates a unique nonce for each request
 * 2. Nonce is injected into HTML <meta property="csp-nonce" content="...">
 * 3. This provider reads the nonce and creates an Emotion cache with it
 * 4. All style tags generated by Emotion will include the nonce attribute
 * 5. CSP allows styles with matching nonce: style-src 'nonce-...'
 *
 * @param children - The subtree that should render under this Emotion cache
 *   (in practice, the entire app). Must be mounted above MUI's
 *   `ThemeProvider`/`CssBaseline` in the provider tree (see `main.tsx`).
 */
export const CspNonceProvider: React.FC<CspNonceProviderProps> = ({ children }) => {
    // Create Emotion cache with nonce support
    // Recomputed only once (empty dep array) — the nonce is fixed for the
    // lifetime of the page load (it's per-request, injected at initial HTML
    // render), so there's no need to recreate the cache on re-renders.
    const cache = useMemo(() => {
        const nonce = getNonce();

        return createCache({
            key: 'mui-style', // Key for Emotion cache
            nonce: nonce, // Nonce for CSP compliance
            prepend: true, // Ensures MUI styles are loaded first
        });
    }, []); // Only create once on mount

    return <CacheProvider value={cache}>{children}</CacheProvider>;
};
